theme: jekyll-theme-minimal
title: Margarita Grushanina
description: I am a PhD candidate at Vienna University of Economics and Business, Institute for Quantitative Economics and Institute for Statistics and Mathematics.
